# Placeholder formula. The real one is generated by goreleaser on the
# first `v*` tag of Root-IO-Labs/open-agent-teams and committed back to
# this tap automatically. Until then we fail fast with a friendly
# message instead of letting Homebrew try to build from a half-wired
# recipe.
class Oat < Formula
  desc "Orchestrate parallel coding agents on GitHub repos"
  homepage "https://github.com/Root-IO-Labs/open-agent-teams"
  license "MIT"
  version "0.0.0"
  url "https://github.com/Root-IO-Labs/open-agent-teams"

  def install
    odie <<~EOS
      `oat` hasn't cut its first versioned release yet, so Homebrew
      install from this tap is not available.

      In the meantime, install from source:

          go install github.com/Root-IO-Labs/open-agent-teams/cmd/oat@latest
          go install github.com/Root-IO-Labs/open-agent-teams/cmd/oat-agent@latest

      Follow release progress at:
          https://github.com/Root-IO-Labs/open-agent-teams/releases
    EOS
  end

  test do
    system "#{bin}/oat", "version"
  end
end
